CREATE TABLE telegram_account_connection (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL UNIQUE REFERENCES auth_user (id),
    telegram_user_id BIGINT,
    telegram_phone_number VARCHAR(32),
    telegram_username VARCHAR(255),
    telegram_display_name VARCHAR(255),
    connection_status VARCHAR(32) NOT NULL,
    premium BOOLEAN NOT NULL DEFAULT FALSE,
    session_directory_key VARCHAR(255),
    session_database_key_ciphertext TEXT,
    default_emoji_status_document_id VARCHAR(64),
    last_sync_error_code VARCHAR(64),
    last_sync_error_message VARCHAR(500),
    last_synced_at TIMESTAMP WITH TIME ZONE,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE telegram_focus_state (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES auth_user (id),
    focus_mode VARCHAR(64) NOT NULL,
    active BOOLEAN NOT NULL DEFAULT FALSE,
    last_activated_at TIMESTAMP WITH TIME ZONE,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT telegram_focus_state_user_mode_unique UNIQUE (user_id, focus_mode)
);

CREATE TABLE telegram_focus_mapping (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES auth_user (id),
    focus_mode VARCHAR(64) NOT NULL,
    emoji_status_document_id VARCHAR(64) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT telegram_focus_mapping_user_mode_unique UNIQUE (user_id, focus_mode)
);

CREATE TABLE telegram_automation_token (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL UNIQUE REFERENCES auth_user (id),
    token_hash CHAR(64) NOT NULL,
    token_hint VARCHAR(32) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    last_used_at TIMESTAMP WITH TIME ZONE,
    revoked_at TIMESTAMP WITH TIME ZONE
);
