CREATE TABLE telegram_mode (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES auth_user (id),
    mode_key VARCHAR(64) NOT NULL,
    emoji_status_document_id VARCHAR(64) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT telegram_mode_user_mode_unique UNIQUE (user_id, mode_key)
);

ALTER TABLE telegram_account_connection
    ADD COLUMN active_mode_id BIGINT REFERENCES telegram_mode (id);

INSERT INTO telegram_mode (user_id, mode_key, emoji_status_document_id, created_at, updated_at)
SELECT
    user_id,
    lower(focus_mode),
    emoji_status_document_id,
    created_at,
    updated_at
FROM telegram_focus_mapping;

WITH ranked_active AS (
    SELECT
        user_id,
        lower(focus_mode) AS mode_key,
        ROW_NUMBER() OVER (
            PARTITION BY user_id
            ORDER BY
                CASE focus_mode
                    WHEN 'SLEEP' THEN 0
                    WHEN 'DO_NOT_DISTURB' THEN 1
                    WHEN 'REDUCE_INTERRUPTIONS' THEN 2
                    WHEN 'AIRPLANE' THEN 3
                    WHEN 'PERSONAL' THEN 4
                    ELSE 100
                END,
                last_activated_at DESC NULLS LAST,
                updated_at DESC,
                id DESC
        ) AS row_num
    FROM telegram_focus_state
    WHERE active = TRUE
)
UPDATE telegram_account_connection connection
SET active_mode_id = mode.id
FROM ranked_active active
JOIN telegram_mode mode
    ON mode.user_id = active.user_id
   AND mode.mode_key = active.mode_key
WHERE connection.user_id = active.user_id
  AND active.row_num = 1;
