ALTER TABLE auth_user
    ADD COLUMN webauthn_user_handle VARCHAR(64);

CREATE UNIQUE INDEX ux_auth_user_webauthn_user_handle
    ON auth_user (webauthn_user_handle)
    WHERE webauthn_user_handle IS NOT NULL;

CREATE TABLE auth_passkey_credential (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES auth_user (id) ON DELETE CASCADE,
    credential_id VARCHAR(1024) NOT NULL UNIQUE,
    public_key_cose BYTEA NOT NULL,
    signature_count BIGINT NOT NULL,
    aaguid UUID,
    transports VARCHAR(255),
    nickname VARCHAR(100) NOT NULL,
    authenticator_attachment VARCHAR(32),
    discoverable BOOLEAN,
    backup_eligible BOOLEAN,
    backup_state BOOLEAN,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    last_used_at TIMESTAMP WITH TIME ZONE,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_auth_passkey_credential_user_id
    ON auth_passkey_credential (user_id);
